### ISSUE TITLE
Create documentation in the README from the project about the usage.

### ISSUE THREAD

**Issue by jabrena** [ev3dev-lang-java/ev3dev-lang-java#678]
It is necessary to write the documentation about the Gradle plugin.
https://github.com/ev3dev-lang-java/gradle-plugin

**Comment by jabrena** [comment]
Fixed

**Comment by JakubVanek** [comment]
No, it's not fixed yet - it was closed only because the zero-diff PR closed.

**Comment by JakubVanek** [comment]
Review pending
